<?php

return [

    'hemat' => [
        'label' => 'Paket Hemat',
        'items' => [
            'Desain Denah Lantai',
            'Desain 3D Eksterior Tampak Depan',
            'Desain 3D Eksterior Tampak Samping Kanan',
            'Desain 3D Eksterior Tampak Samping Kiri',
            'Desain 3D Eksterior Tampak Atas',
            'Desain 3D Eksterior Tampak Mata Burung Kanan',
            'Desain 3D Eksterior Tampak Mata Burung Kiri',
            'Potongan A-A',
            'Potongan B-B',
            '*Free Revisi Tanpa Batas',
            '*Free Konsultasi & Zoom Meeting dengan Arsitek dan Engineer',
            '*Fasilitas Group Tim dengan Arsitek dan Engineer',
        ],
    ],

    'interior' => [
        'label' => 'Paket Interior',
        'items' => [
            'Desain 3D Interior Seluruh Ruangan (Beberapa View)',
            'Detail 3D Interior Seluruh Ruangan (Beberapa View)',
            'Video Animasi Eksterior dan Interior',
            '*Free Revisi Tanpa Batas',
            '*Free Konsultasi & Zoom Meeting dengan Arsitek dan Engineer',
            '*Fasilitas Group Tim dengan Arsitek dan Engineer',
        ],
    ],

    'premium' => [
        'label' => 'Paket Premium',
        'items' => [
            'Desain Denah Lantai',
            'Desain 3D Eksterior Tampak Depan',
            'Desain 3D Eksterior Tampak Samping Kanan',
            'Desain 3D Eksterior Tampak Samping Kiri',
            'Desain 3D Eksterior Tampak Atas',
            'Desain 3D Eksterior Tampak Mata Burung Kanan',
            'Desain 3D Eksterior Tampak Mata Burung Kiri',
            'Desain 3D Interior Seluruh Ruangan (Beberapa View)',
            'Detail 3D Interior Seluruh Ruangan (Beberapa View)',
            'Video Animasi Eksterior dan Interior',
            'Potongan A-A',
            'Potongan B-B',
            'Perhitungan RAB (Rencana Anggaran Biaya)',
            '*Free Revisi Tanpa Batas',
            '*Free Konsultasi & Zoom Meeting dengan Arsitek dan Engineer',
            '*Fasilitas Group Tim dengan Arsitek dan Engineer',
        ],
    ],

    'eksekutif' => [
        'label' => 'Paket Eksekutif',
        'items' => [
            'Desain Denah Lantai',
            'Desain 3D Eksterior Tampak Depan',
            'Desain 3D Eksterior Tampak Samping Kanan',
            'Desain 3D Eksterior Tampak Samping Kiri',
            'Desain 3D Eksterior Tampak Atas',
            'Desain 3D Eksterior Tampak Mata Burung Kanan',
            'Desain 3D Eksterior Tampak Mata Burung Kiri',
            'Potongan A-A',
            'Potongan B-B',
            'Desain Denah 2D Tampak Depan',
            'Desain Denah 2D Tampak Samping Kanan',
            'Desain Denah 2D Tampak Samping Kiri',
            'Desain Denah 2D Tampak Belakang',
            'Desain Denah 2D Rencana Pola Lantai',
            'Desain Denah 2D Rencana Plafond',
            'Desain Denah 2D Rencana Elektrikal',
            'Desain Denah 2D Rencana Atap Hujan',
            'Desain Denah 2D Rencana Air Bersih',
            'Desain Denah 2D Rencana Air Kotor',
            'Desain Detail 2D Tangga',
            'Desain Detail 2D Kusen Pintu dan Jendela',
            'Desain Detail 2D Kusen Kamar Mandi',
            'Desain Detail 2D Sumur Resapan',
            'Desain Detail 2D Septictank',
            'Desain Detail 2D Bak Kontrol',
            'Perhitungan RAB',
            '*Free Revisi Tanpa Batas',
            '*Free Konsultasi & Zoom Meeting dengan Arsitek dan Engineer',
            '*Fasilitas Group Tim dengan Arsitek dan Engineer',
        ],
    ],

    'lengkap' => [
        'label' => 'Paket Lengkap',
        'items' => [
            'Desain Denah Lantai',
            'Desain 3D Eksterior Tampak Depan',
            'Desain 3D Eksterior Tampak Samping Kanan',
            'Desain 3D Eksterior Tampak Samping Kiri',
            'Desain 3D Eksterior Tampak Atas',
            'Desain 3D Eksterior Tampak Mata Burung Kanan',
            'Desain 3D Eksterior Tampak Mata Burung Kiri',
            'Potongan A-A',
            'Potongan B-B',
            'Potongan Portal Memanjang',
            'Potongan Portal Melintang',
            'Desain Denah 2D Rencana Pondasi',
            'Desain Denah 2D Rencana Sloof',
            'Desain Denah 2D Rencana Kolom',
            'Desain Denah 2D Rencana Balok',
            'Desain Denah 2D Rencana Plat Lantai',
            'Desain Denah 2D Rencana Plat Atap',
            'Desain Denah 2D Tampak Depan',
            'Desain Denah 2D Tampak Samping Kanan',
            'Desain Denah 2D Tampak Samping Kiri',
            'Desain Denah 2D Tampak Belakang',
            'Desain Denah 2D Rencana Pola Lantai',
            'Desain Denah 2D Rencana Plafond',
            'Desain Denah 2D Rencana Elektrikal',
            'Desain Denah 2D Rencana Atap Hujan',
            'Desain Denah 2D Rencana Air Bersih',
            'Desain Denah 2D Rencana Air Kotor',
            'Desain Detail 2D Tangga',
            'Desain Detail 2D Kuda-kuda',
            'Desain Detail 2D Kusen Pintu dan Jendela',
            'Desain Detail 2D Kusen Kamar Mandi',
            'Desain Detail 2D Sumur Resapan',
            'Desain Detail 2D Septictank',
            'Desain Detail 2D Bak Kontrol',
            'Perhitungan RAB',
            '*Free Revisi Tanpa Batas',
            '*Free Konsultasi & Zoom Meeting dengan Arsitek dan Engineer',
            '*Fasilitas Group Tim dengan Arsitek dan Engineer',
        ],
    ],

    'struktur' => [
        'label' => 'Paket Hitung Struktur',
        'items' => [
            'Desain Denah 2D Rencana Pondasi',
            'Desain Denah 2D Rencana Sloof',
            'Desain Denah 2D Rencana Kolom',
            'Desain Denah 2D Rencana Balok',
            'Desain Denah 2D Rencana Plat Lantai',
            'Desain Denah 2D Rencana Plat Atap',
            'Desain Denah 2D Rencana Dimensi Ukuran',
            'Desain Denah 2D Rencana Penulangan Besi',
            'Desain Denah 2D Potongan Portal Memanjang',
            'Desain Denah 2D Potongan Portal Melintang',
            'Laporan Struktur meliputi Peraturan SNI dan Standard Struktur',
        ],
    ],

    'pbg' => [
        'label' => 'Paket PBG',
        'items' => [
            'Spesifikasi Teknis Arsitektur',
            'Spesifikasi Teknis Struktur',
            'Spesifikasi Teknis MEP',
            'Desain Denah Lantai',
            'Desain 3D Eksterior Tampak Depan',
            'Desain 3D Eksterior Tampak Samping Kanan',
            'Desain 3D Eksterior Tampak Samping Kiri',
            'Desain 3D Eksterior Tampak Atas',
            'Desain 3D Eksterior Tampak Mata Burung Kanan',
            'Desain 3D Eksterior Tampak Mata Burung Kiri',
            'Potongan A-A',
            'Potongan B-B',
            'Potongan Portal Memanjang',
            'Potongan Portal Melintang',
            'Desain Denah 2D Rencana Pondasi',
            'Desain Denah 2D Rencana Sloof',
            'Desain Denah 2D Rencana Kolom',
            'Desain Denah 2D Rencana Balok',
            'Desain Denah 2D Rencana Plat Lantai',
            'Desain Denah 2D Rencana Plat Atap',
            'Desain Denah 2D Tampak Depan',
            'Desain Denah 2D Tampak Samping Kanan',
            'Desain Denah 2D Tampak Samping Kiri',
            'Desain Denah 2D Tampak Belakang',
            'Desain Denah 2D Rencana Pola Lantai',
            'Desain Denah 2D Rencana Plafond',
            'Desain Denah 2D Rencana Elektrikal',
            'Desain Denah 2D Rencana Atap Hujan',
            'Desain Denah 2D Rencana Air Bersih',
            'Desain Denah 2D Rencana Air Kotor',
            'Desain Detail 2D Tangga',
            'Desain Detail 2D Kuda-kuda',
            'Desain Detail 2D Kusen Pintu dan Jendela',
            'Desain Detail 2D Kusen Kamar Mandi',
            'Desain Detail 2D Sumur Resapan',
            'Desain Detail 2D Septictank',
            'Desain Detail 2D Bak Kontrol',
            'Perhitungan RAB',
            'RKS Rencana Kerja dan Syarat-syarat',
            'Laporan Struktur meliputi Peraturan SNI dan Standard Struktur',
            'Surat Pernyataan Pertanggungjawaban Mutu Perencanaan',
            'Dokumen Legalitas Perencana (Copy SKA/SKK)',
            '*Free Revisi Tanpa Batas',
            '*Free Konsultasi & Zoom Meeting dengan Arsitek dan Engineer',
            '*Fasilitas Group Tim dengan Arsitek dan Engineer',
        ],
    ],

    'slf' => [
        'label' => 'Paket SLF',
        'items' => [
            'Laporan Pemeriksaan Kelaikan Struktur',
            'Laporan Pemeriksaan Kelaikan Arsitektur',
            'Laporan Pemeriksaan Kelaikan Utilitas (MEP)',
            'Hasil Uji Hambatan Pembumian (Grounding Test)',
            'Rekomendasi / Suket Disnaker',
            'Hasil Uji Kualitas Air Bersih',
            'As-Built Drawings',
        ],
    ],

];
